apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.consumerService.image }}:{{ .Values.consumerService.tag }}"
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: MONGO_HOST
              value: {{ .Release.Name }}-mongodb-headless
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: {{ .Values.consumerService.mongoUser }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.consumerService.mongoPasswordSecret . }}
                  key: {{ .Values.consumerService.mongoPasswordSecretKey }}
            - name: MONGO_DB_NAME
              value: "consumers"

            # Kafka configuration
            - name: KAFKA_BROKERS_CSV
              value: {{ tpl .Values.consumerService.kafkaBrokers . }}
            - name: KAFKA_GROUP_ID
              value: {{ .Values.consumerService.serviceId }}

            # Other group IDs
            - name: CONSUMER_SERVICE_GROUP_ID
              value: {{ .Values.consumerService.serviceId }}
            - name: PAGE_CAPTURE_SERVICE_GROUP_ID
              value: {{ .Values.pageCaptureService.serviceId }}
            - name: SCREENSHOT_META_SERVICE_GROUP_ID
              value: {{ .Values.screenshotMetaService.serviceId }}
            - name: NOTIFICATION_SERVICE_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}
            - name: SCREENSHOT_REQUEST_SERVICE_GROUP_ID
              value: {{ .Values.screenshotRequestsService.serviceId }}

            # tracing
            - name: OTEL_TRACE_COLLECTOR_URL
              value: 'http://{{ .Release.Name }}-jaeger-collector:4317'
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"