apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-notifications-service
spec:
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: "maks113/valid-page-notification-service:1.0.1"
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"

              # Mongo
            - name: MONGO_HOST
              value: {{ .Release.Name }}-mongodb-headless
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: {{ .Values.notificationService.mongoUser }}
            - name: MONGO_PASSWORD
              value: {{ .Values.notificationService.mongoPassword }}
            - name: MONGO_DB_NAME
              value: "notifications"

            # Kafka configuration
            - name: KAFKA_BROKERS_CSV
              value: "{{ .Release.Name }}-kafka-controller-headless:9092"
            - name: KAFKA_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}

            # Other group IDs
            - name: CONSUMER_SERVICE_GROUP_ID
              value: {{ .Values.consumerService.serviceId }}
            - name: PAGE_CAPTURE_SERVICE_GROUP_ID
              value: {{ .Values.pageCaptureService.serviceId }}
            - name: SCREENSHOT_META_SERVICE_GROUP_ID
              value: {{ .Values.screenshotMetaService.serviceId }}
            - name: NOTIFICATION_SERVICE_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}
            - name: SCREENSHOT_REQUEST_SERVICE_GROUP_ID
              value: {{ .Values.screenshotRequestsService.serviceId }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"