apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-notifications
spec:
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: "{{ .Values.notificationService.image }}:{{ .Values.notificationService.tag }}"
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"

            # Kafka configuration
            - name: KAFKA_BROKERS_CSV
              value: {{ tpl .Values.notificationService.kafkaBrokers . }}
            - name: KAFKA_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}

            # Other group IDs
            - name: CONSUMER_SERVICE_GROUP_ID
              value: {{ .Values.consumerService.serviceId }}
            - name: PAGE_CAPTURE_SERVICE_GROUP_ID
              value: {{ .Values.pageCaptureService.serviceId }}
            - name: SCREENSHOT_META_SERVICE_GROUP_ID
              value: {{ .Values.screenshotMetaService.serviceId }}
            - name: NOTIFICATION_SERVICE_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}
            - name: SCREENSHOT_REQUEST_SERVICE_GROUP_ID
              value: {{ .Values.screenshotRequestsService.serviceId }}

            # tracing
            - name: OTEL_TRACE_COLLECTOR_URL
              value: 'http://{{ .Release.Name }}-jaeger-collector:4317'
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"