apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-notifications-service
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: notifications