apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-arch-homework-ingress-users
spec:
  ingressClassName: nginx
  rules:
    - host: "users.arch.homework"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Release.Name }}-app-service-users
                port:
                  number: {{ .Values.users.port }}
