apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service-users
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-arch-homework-users
  ports:
    - port: {{ .Values.users.port }}
      targetPort: {{ .Values.users.port }}
