apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args: ["start-dev"]
          env:
            - name: KC_HOSTNAME
              value: "localhost"
            - name: KC_HOSTNAME_PORT
              value: "8080"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_LOG_LEVEL
              value: "info"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_DB
              value: {{ .Values.postgres.bdName }}
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ include "fullname" . }}-postgres-service:5432/{{ .Values.postgres.bdName }}"
            - name: KC_DB_USERNAME
              value: {{ .Values.postgres.bdName }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.adminPassword }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
