export const CONSUMER_SERVICE = 'CONSUMER_SERVICE';
export const PAGE_CAPTURE_SERVICE = 'PAGE_CAPTURE_SERVICE';
export const SCREENSHOT_META_SERVICE = 'SCREENSHOT_META_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const SCREENSHOT_REQUEST_SERVICE = 'SCREENSHOT_REQUEST_SERVICE';