apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-grafana-service
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: grafana