apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}-configmap
data:
  server.properties: |
    # KRaft Configuration
    process.roles=broker,controller
    node.id=${NODE_ID}
    controller.quorum.voters={{ include "kafka.quorum-voters" . | trim }}

    # Network
    listeners={{ .Values.configuration.listeners }}
    advertised.listeners={{ .Values.configuration.advertisedListeners }}
    listener.security.protocol.map={{ .Values.configuration.listenerSecurityProtocols }}

    # Topic Configuration
    num.partitions={{ .Values.configuration.numPartitions }}
    default.replication.factor={{ .Values.configuration.defaultReplicationFactor }}
    min.insync.replicas={{ .Values.configuration.minInsyncReplicas }}