apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.headless-service" . }}
spec:
  clusterIP: None
  ports:
    - name: client
      port: 9092
    - name: controller
      port: 9093
  selector:
    app: {{ include "kafka.fullname" . }}
