apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-arch-homework
  labels:
    app: {{ .Release.Name }}-arch-homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-arch-homework
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-arch-homework
    spec:
      containers:
        - name: arch-homework
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-app-config
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.app.mongo.password.secret.name . }}
                  key: {{ .Values.app.mongo.password.secret.key }}
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: 8000
          readinessProbe:
            httpGet:
              path: /healthcheck/
              port: 8000
        - name: gatekeeper
          image: quay.io/gogatekeeper/gatekeeper:1.4.2
          args:
            - '--config'
            - /etc/gatekeeper/config.yaml
          ports:
            - containerPort: 3000
              name: api
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/gatekeeper
              name: gatekeeper-config
      volumes:
        - name: gatekeeper-config
          secret:
            secretName: {{ .Release.Name }}-gatekeeper-secret
            defaultMode: 420