apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service-billing
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-arch-homework-billing
  ports:
    - port: {{ .Values.billing.port }}
      targetPort: {{ .Values.billing.port }}
