apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-keycloak-service
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: minio