apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-consumer-service
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: consumer-service