apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-arch-homework-ingress-orders
spec:
  ingressClassName: nginx
  rules:
    - host: "orders.arch.homework"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Release.Name }}-app-service-orders
                port:
                  number: {{ .Values.orders.port }}
