apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service-notifications
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-arch-homework-notifications
  ports:
    - port: {{ .Values.notifications.port }}
      targetPort: {{ .Values.notifications.port }}
