apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
data:
  MONGO_HOST: "{{ tpl .Values.mongo.hostTpl . }}"
  MONGO_PORT: "{{ .Values.mongo.port }}"
  MONGO_USER: "{{ .Values.mongo.user }}"