version: "3.9"
services:
  app:
    platform: 'linux/amd64'
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
#    entrypoint: sleep infinity
