apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-screenshot-meta
spec:
  selector:
    matchLabels:
      app: screenshot-meta
  template:
    metadata:
      labels:
        app: screenshot-meta
    spec:
      containers:
        - name: screenshot-meta
          image: "{{ .Values.screenshotMetaService.image }}:{{ .Values.screenshotMetaService.tag }}"
          ports:
            - containerPort: 8004
          env:
            - name: PORT
              value: "8004"

              # Mongo
            - name: MONGO_HOST
              value: {{ .Release.Name }}-mongodb-headless
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: {{ .Values.screenshotMetaService.mongoUser }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.screenshotMetaService.mongoPasswordSecret . }}
                  key: {{ .Values.screenshotMetaService.mongoPasswordSecretKey }}
            - name: MONGO_DB_NAME
              value: "screenshot-meta"

            # Kafka configuration
            - name: KAFKA_BROKERS_CSV
              value: {{ tpl .Values.screenshotMetaService.kafkaBrokers . }}
            - name: KAFKA_GROUP_ID
              value: {{ .Values.screenshotMetaService.serviceId }}

            # MinIO configuration
            - name: MINIO_ENDPOINT
              value: {{ .Release.Name }}-minio
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.screenshotMetaService.minio.accessKey }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.screenshotMetaService.minio.secretKey }}
            - name: MINIO_BUCKET
              value: {{ .Values.screenshotMetaService.minio.bucket }}

            # Other group IDs
            - name: CONSUMER_SERVICE_GROUP_ID
              value: {{ .Values.consumerService.serviceId }}
            - name: PAGE_CAPTURE_SERVICE_GROUP_ID
              value: {{ .Values.pageCaptureService.serviceId }}
            - name: SCREENSHOT_META_SERVICE_GROUP_ID
              value: {{ .Values.screenshotMetaService.serviceId }}
            - name: NOTIFICATION_SERVICE_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}
            - name: SCREENSHOT_REQUEST_SERVICE_GROUP_ID
              value: {{ .Values.screenshotRequestsService.serviceId }}

            # tracing
            - name: OTEL_TRACE_COLLECTOR_URL
              value: 'http://{{ .Release.Name }}-jaeger-collector:4317'
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"