apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-screenshot-meta-service
spec:
  type: ClusterIP
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: screenshot-meta