apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-page-capture
spec:
  replicas: {{ .Values.pageCaptureService.replicas }}
  selector:
    matchLabels:
      app: page-capture
  template:
    metadata:
      labels:
        app: page-capture
    spec:
      containers:
        - name: page-capture
          image: "{{ .Values.pageCaptureService.image }}:{{ .Values.pageCaptureService.tag }}"
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"

              # Mongo
            - name: MONGO_HOST
              value: {{ .Release.Name }}-mongodb-headless
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: {{ .Values.screenshotMetaService.mongoUser }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.screenshotMetaService.mongoPasswordSecret . }}
                  key: {{ .Values.screenshotMetaService.mongoPasswordSecretKey }}
            - name: MONGO_DB_NAME
              value: "page-capture"

            # Kafka configuration
            - name: KAFKA_BROKERS_CSV
              value: {{ tpl .Values.pageCaptureService.kafkaBrokers . }}
            - name: KAFKA_GROUP_ID
              value: {{ .Values.pageCaptureService.serviceId }}

            # MinIO configuration
            - name: MINIO_ENDPOINT
              value: {{ .Release.Name }}-minio
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.pageCaptureService.minio.accessKey }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.pageCaptureService.minio.secretKey }}
            - name: MINIO_BUCKET
              value: {{ .Values.pageCaptureService.minio.bucket }}

            # Puppeteer configuration
            - name: PUPPETEER_EXECUTABLE_PATH
              value: "/usr/bin/chromium"

            # Other group IDs
            - name: CONSUMER_SERVICE_GROUP_ID
              value: {{ .Values.consumerService.serviceId }}
            - name: PAGE_CAPTURE_SERVICE_GROUP_ID
              value: {{ .Values.pageCaptureService.serviceId }}
            - name: SCREENSHOT_META_SERVICE_GROUP_ID
              value: {{ .Values.screenshotMetaService.serviceId }}
            - name: NOTIFICATION_SERVICE_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}
            - name: SCREENSHOT_REQUEST_SERVICE_GROUP_ID
              value: {{ .Values.screenshotRequestsService.serviceId }}

            # tracing
            - name: OTEL_TRACE_COLLECTOR_URL
              value: 'http://{{ .Release.Name }}-jaeger-collector:4317'
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"