apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-jaeger-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: jaeger.arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-jaeger-query
                port:
                  number: 16686
