apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-mongo-key
data:
  mongo.key: |
    BVkxcEUSyaJhOHNfSDomuFw3oZ6RlufjtTLurwkhsH+IJpWSTkI2mKlOQk2qzP91
    kn3sNTbFV4owcru2V30utKt78QF3rrDpIKn14bkPomz2hULDStiJ9DeyUmBGWfw0
    JbfD9FQUo9BwudHFBdPUP4wTfHDZgTt0JjZwVrkJ3ro6bJ03PJLTt4eBH8dTS2N8
    PZlUc+fFzemnxgZ1a6L64ccowMAkTRCx7dqpNqDdHzE9z/Olx1Ued+oGNUxmuaRD
    Ab4uBtal7Fecb33mfq0nNeotoF2PDhWCdwl/xEYMROA6dPHJoX4BauWWAqGRjKtk
    HGttDf1f1M6U0nhcmGrr0ocDTwMZxyXKbO+y7d7pOdglO0dTejhmt2vIBSlRDCKA
    G9DtlVfIXeDNdGK1YAC9BfZzWa8GMS3SSmbEjcGI4y9g4tJ393JDO2ZiUSuF18F7
    lbq/bkRzAeQY0A5EJ4u0IOnZj6i+ofXw0OeDu1KUtiwOEuzOBan174Dxz7RXtsC3
    KnOHh9kJoJZSvekN5AH9RyTCOp2kT/mqbka8NR0kGkbpfroX78SM+O0qwq7DsEl5
    34ganzMMJd2MtcPueDYHCG0dYryAkV6ySTTtDlmZ9y4XEV3V3s9Hg6hA/xp1GsIE
    CiR0rFJDUYi7hKRF7+aleTYJgS9B0JxI2mFjZ3DfTn6NwCC47J2V2feiNTiol16O
    A6XajAbXZscELA9XLHz/4iXKHPtBguiUTrzGvLvMU5sf8AUJ/KViXyxMDv65yo5o
    KuEPfW+da7NYw7GBESdydpCUsGXk2L7cg7QdekYKLU9L1ZSQ4WrHfCSWXm19ojkW
    KDYffb6vXywTowPxxh++O/MDiBdC6Du38yEXXN6/dduHJt5qPcOpHeWK2wOHpFOL
    LfCDuOODfbS+B+M9OJV1Xv9jeDLqHzZ/Icbxn5npOPvoo00KcK98rjdEZI6vN+ez
    GjdOUwpruTy9cCr0vSsYiRjs98NzmJzX9K+NKo+0YAWc65H2
