{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(request_count[$__rate_interval])",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "rate(sum(nginx_ingress_controller_requests{host=\"arch.homework\"})[$__rate_interval:$__interval])",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "[app] Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(latency_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "app: .5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "app: .95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "app: .99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(latency_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "app: 1"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(error_count[$__rate_interval])",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "rate(sum(nginx_ingress_controller_requests{host='arch.homework', status=~'5..'})[$__rate_interval:$__interval])",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "[nginx] Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "nginx: .5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "nginx: .95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "nginx: .99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "nginx: 1"
    }
   ]
  }
 ]
}