apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kafka'
        static_configs:
          - targets: [ '{{ include "fullname" . }}-kafka-service:9092' ]
      - job_name: 'minio'
        static_configs:
          - targets: [ '{{ include "fullname" . }}-minio-service:9000' ]
      - job_name: 'consumer-service'
        static_configs:
            - targets: [ '{{ include "fullname" . }}-consumer-service:8002' ]
      - job_name: 'screenshot-requests'
        static_configs:
          - targets: [ '{{ include "fullname" . }}-screenshot-requests-service:8000' ]
      - job_name: 'notifications'
        static_configs:
          - targets: [ '{{ include "fullname" . }}-notifications-service:8001' ]
      - job_name: 'page-capture'
        static_configs:
          - targets: [ '{{ include "fullname" . }}-page-capture-service:8003' ]
      - job_name: 'screenshot-meta'
        static_configs:
          - targets: [ '{{ include "fullname" . }}-screenshot-meta-service:8004' ]