apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-minio-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: "minio.arch.homework"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}-minio
                port:
                  number: 9001
