replicaCount: &replicasCnt 1
clusterId: "ZgYhN123S8q9r7QwRDqriA"

image:
  repository: bitnami/kafka
  tag: 3.9.0
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""
  accessModes: [ "ReadWriteOnce" ]

configuration:
  listeners: PLAINTEXT://:9092,CONTROLLER://:9093
  advertisedListeners: PLAINTEXT://{{ .Release.Name }}-kafka-{{ .Values.replicaCount }}.{{ .Release.Name }}-headless.{{ .Release.Namespace }}.svc.cluster.local:9092
  numPartitions: 1
  defaultReplicationFactor: *replicasCnt
  minInsyncReplicas: 2
  listenerSecurityProtocols: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

resources:
  requests:
    memory: 100Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 1000m