apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-page-capture
spec:
  selector:
    matchLabels:
      app: page-capture
  template:
    metadata:
      labels:
        app: page-capture
    spec:
      containers:
        - name: page-capture
          image: "maks113/valid-page-page-capture-service"
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"

              # Mongo
            - name: MONGO_HOST
              value: {{ include "fullname" . }}-mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: {{ .Values.mongo.username }}
            - name: MONGO_PASSWORD
              value: {{ .Values.mongo.password }}
            - name: MONGO_DB_NAME
              value: "notifications"

            # Kafka configuration
            - name: KAFKA_BROKERS_CSV
              value: "{{ include "fullname" . }}-kafka-service:9092"
            - name: KAFKA_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}

            # MinIO configuration
            - name: MINIO_ENDPOINT
              value: {{ include "fullname" . }}-minio-service
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.accessKey }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.minio.secretKey }}
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucket }}

            # Puppeteer configuration
            - name: PUPPETEER_EXECUTABLE_PATH
              value: "/usr/bin/chromium"

            # Other group IDs
            - name: CONSUMER_SERVICE_GROUP_ID
              value: {{ .Values.consumerService.serviceId }}
            - name: PAGE_CAPTURE_SERVICE_GROUP_ID
              value: {{ .Values.pageCaptureService.serviceId }}
            - name: SCREENSHOT_META_SERVICE_GROUP_ID
              value: {{ .Values.screenshotMetaService.serviceId }}
            - name: NOTIFICATION_SERVICE_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}
            - name: SCREENSHOT_REQUEST_SERVICE_GROUP_ID
              value: {{ .Values.screenshotRequestsService.serviceId }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"