apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-screenshot-requests
spec:
  selector:
    matchLabels:
      app: screenshot-requests
  template:
    metadata:
      labels:
        app: screenshot-requests
    spec:
      containers:
        - name: screenshot-requests
          image: "{{ .Values.screenshotRequestsService.image }}:{{ .Values.screenshotRequestsService.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"

              # Mongo
            - name: MONGO_HOST
              value: {{ .Release.Name }}-mongodb-headless
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: {{ .Values.screenshotRequestsService.mongoUser }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.screenshotRequestsService.mongoPasswordSecret . }}
                  key: {{ .Values.screenshotRequestsService.mongoPasswordSecretKey }}
            - name: MONGO_DB_NAME
              value: "screenshot-requests"

            # Kafka configuration
            - name: KAFKA_BROKERS_CSV
              value: {{ tpl .Values.screenshotRequestsService.kafkaBrokers . }}
            - name: KAFKA_GROUP_ID
              value: {{ .Values.screenshotRequestsService.serviceId }}

            # Other group IDs
            - name: CONSUMER_SERVICE_GROUP_ID
              value: {{ .Values.consumerService.serviceId }}
            - name: PAGE_CAPTURE_SERVICE_GROUP_ID
              value: {{ .Values.pageCaptureService.serviceId }}
            - name: SCREENSHOT_META_SERVICE_GROUP_ID
              value: {{ .Values.screenshotMetaService.serviceId }}
            - name: NOTIFICATION_SERVICE_GROUP_ID
              value: {{ .Values.notificationService.serviceId }}
            - name: SCREENSHOT_REQUEST_SERVICE_GROUP_ID
              value: {{ .Values.screenshotRequestsService.serviceId }}

            # tracing
            - name: OTEL_TRACE_COLLECTOR_URL
              value: 'http://{{ .Release.Name }}-jaeger-collector:4317'
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

        - name: gatekeeper
          image: quay.io/gogatekeeper/gatekeeper:1.4.2
          args:
            - '--config'
            - /etc/gatekeeper/config.yaml
          ports:
            - containerPort: 3000
              name: api
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/gatekeeper
              name: gatekeeper-config
      volumes:
        - name: gatekeeper-config
          secret:
            secretName: {{ .Release.Name }}-gatekeeper-secret
            defaultMode: 420
