apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gatekeeper-secret
stringData:
  config.yaml: |
    client-id: valid-page
    client-secret: PoXZsnHwCiFAdI7KFPWsAbXaxH6QDlmt
    discovery-url: http://keycloak.arch.homework/realms/valid-page/.well-known/openid-configuration
    enable-default-deny: true
    enable-logout-redirect: true
    enable-json-logging: true
    enable-metrics: false
    enable-refresh-tokens: true
    enable-session-cookies: false
    store-url: redis://valid-page-redis-replicas:6379
    no-redirects: true
    encryption-key: aD3P1N5yVuI64gEzihF2SVCyCSB0TmiU
    skip-openid-provider-tls-verify: true
    skip-access-token-clientid-check: true
    listen: :3000
    listen-admin: :4000
    cors-origins:
     - '*'
    cors-credentials: true

    ingress.enabled: true

    enableLogoutRedirect: true
    enableRefreshTokens: true
    enableSessionCookies: true
    skipAccessTokenClientIdCheck: true
    secure-cookie: false
    redirection-url: http://arch.homework
    upstream-url: http://127.0.0.1:8000
    server-read-timeout: 600s
    server-write-timeout: 600s
    server-idle-timeout: 600s
    upstream-response-header-timeout: 600s
    verbose: true
    scopes:
      - email
    add-claims:
    - given_name
    - family_name
    - session_state
    tags:
      title: Вход
      activeDirectory: oidc
    resources:
      - uri: /static/*
        methods:
        - GET
        white-listed: true
      - uri: /favicon.ico
        methods:
        - GET
        white-listed: true
      - uri: /site.webmanifest
        methods:
        - GET
        white-listed: true
      - uri: /healthcheck
        methods:
        - GET
        white-listed: true