apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-screenshot-requests-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      name: api
      targetPort: 8000
    - port: 3000
      name: gatekeeper
      targetPort: 3000
  selector:
    app: screenshot-requests