screenshotRequestsService:
  image: maks113/valid-page-screenshot-requests-service
  serviceId: screenshot-requests

consumerService:
  image: maks113/valid-page-consumer-service
  serviceId: consumer

pageCaptureService:
  image: maks113/valid-page-page-capture-service
  serviceId: page-capture

screenshotMetaService:
  image: maks113/valid-screenshot-meta-service
  serviceId: screenshot-meta

notificationService:
  image: maks113/valid-page-notification-service
  serviceId: notifications

kafka:
  image: bitnami/kafka:3.9.0
  replicas: 1
  volumeSize: 200Mi

keycloak:
  image: quay.io/keycloak/keycloak:23.0.7
  adminUser: admin
  adminPassword: admin

postgres:
  replicas: 1
  image: postgres:15
  bdName: keycloak
  volumeSize: 200Mi
  username: keycloak
  password: password

minio:
  replicas: 1
  image: minio/minio:latest
  volumeSize: 200Mi
  rootUser: minioadmin
  rootPassword: minioadmin
  bucket: screenshots
  accessKey: ''
  secretKey: ''

mongo:
  replicas: 1
  image: mongo:4.4.18
  volumeSize: 200Mi
  username: root
  password: example

grafana:
  adminUser: admin
  adminPassword: admin
  datasources:
    prometheus:
      url: 1
      access: 2
      isDefault: true